### ISSUE TITLE
Unable to run in local browser

### ISSUE THREAD

**Issue by springpong** [justalever/tailwind-navbar#1]
Hi Andy,

I really enjoyed learning from your video and was super excited about using Tailwind for one of my team projects.

Unfortunately, after downloaded your project, I'm having issues with getting it to display on the local browser with npm start; npm run serve, yarn, or yarn run serve.  I tried separately installing the following methods after deleting the node folder: npm install; yarn; and npm install tailwinds postcss-cli autoprefixer, then run the server commands according to it's method, but got tons of error running the serve commands.
![Tailwind nav bar error Pt 1](https://user-images.githubusercontent.com/52018618/75932565-9c2d2e00-5e2c-11ea-9703-dda654be790a.png)
![Tailwind nav bar error Pt 2](https://user-images.githubusercontent.com/52018618/75932569-9fc0b500-5e2c-11ea-9482-be701a017662.png)

I would love getting your insight.

**Comment by Tjark-Kuehl** [comment]
I think you're running an old node version. The 'unexpected token ...' means your version is not supporting the rest spread operator. 
Try updating your node version and checking and/or checking with 'node --version' if its up to date.
I just tried it with the newest version of node and it worked like a charm

**Comment by springpong** [comment]
Tjark-Kuehl,
thank you. You're absolutely right.  For unknown reason the node version is default at V8.0.0.  I have to $ MVN 8.10.0 in order to switch each time, but it works after switching.
